TYPE=VIEW
query=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`a`.`parent` AS `parent`,`a`.`flag_active` AS `flag_active`,`a`.`flag_header` AS `flag_header`,`a`.`is_income` AS `is_income`,`a`.`is_balance_sheet` AS `is_balance_sheet`,`a`.`notes` AS `notes`,`a`.`def_position` AS `def_position`,`a`.`modified_user` AS `modified_user`,`a`.`created_date` AS `created_date`,`a`.`modified_date` AS `modified_date`,`a`.`created_user` AS `created_user`,`a`.`beg_balance` AS `beg_balance`,`a`.`golongan` AS `golongan`,`b`.`account_name` AS `header`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select (case when isnull(`ideaccounting_dev`.`i_project_name`.`header_text`) then \'\' else `ideaccounting_dev`.`i_project_name`.`header_text` end) AS `header_text` from `ideaccounting_dev`.`i_project_name` where (`ideaccounting_dev`.`i_project_name`.`project_default` = 1)) AS `header_text` from (`ideaccounting_dev`.`mst_account` `a` join `ideaccounting_dev`.`coa_header_view` `b` on((`b`.`id_account` = `a`.`parent`))) where (`a`.`flag_header` = 0)
md5=0af08f14cacf30ed287976ee07cc0b53
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:31:59
create-version=1
source=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`a`.`parent` AS `parent`,`a`.`flag_active` AS `flag_active`,`a`.`flag_header` AS `flag_header`,`a`.`is_income` AS `is_income`,`a`.`is_balance_sheet` AS `is_balance_sheet`,`a`.`notes` AS `notes`,`a`.`def_position` AS `def_position`,`a`.`modified_user` AS `modified_user`,`a`.`created_date` AS `created_date`,`a`.`modified_date` AS `modified_date`,`a`.`created_user` AS `created_user`,`a`.`beg_balance` AS `beg_balance`,`a`.`golongan` AS `golongan`,`b`.`account_name` AS `header`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select (case when isnull(`i_project_name`.`header_text`) then \'\' else `i_project_name`.`header_text` end) AS `header_text` from `i_project_name` where (`i_project_name`.`project_default` = 1)) AS `header_text` from (`mst_account` `a` join `coa_header_view` `b` on((`b`.`id_account` = `a`.`parent`))) where (`a`.`flag_header` = 0)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`a`.`parent` AS `parent`,`a`.`flag_active` AS `flag_active`,`a`.`flag_header` AS `flag_header`,`a`.`is_income` AS `is_income`,`a`.`is_balance_sheet` AS `is_balance_sheet`,`a`.`notes` AS `notes`,`a`.`def_position` AS `def_position`,`a`.`modified_user` AS `modified_user`,`a`.`created_date` AS `created_date`,`a`.`modified_date` AS `modified_date`,`a`.`created_user` AS `created_user`,`a`.`beg_balance` AS `beg_balance`,`a`.`golongan` AS `golongan`,`b`.`account_name` AS `header`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select (case when isnull(`ideaccounting_dev`.`i_project_name`.`header_text`) then \'\' else `ideaccounting_dev`.`i_project_name`.`header_text` end) AS `header_text` from `ideaccounting_dev`.`i_project_name` where (`ideaccounting_dev`.`i_project_name`.`project_default` = 1)) AS `header_text` from (`ideaccounting_dev`.`mst_account` `a` join `ideaccounting_dev`.`coa_header_view` `b` on((`b`.`id_account` = `a`.`parent`))) where (`a`.`flag_header` = 0)
