TYPE=VIEW
query=select (case when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end) AS `period`,count(`ideaccounting_dev`.`trn_request_order_head`.`no_request_order`) AS `jumlah` from `ideaccounting_dev`.`trn_request_order_head` where (year(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = (select `ideaccounting_dev`.`i_accounting_period`.`year` from `ideaccounting_dev`.`i_accounting_period`)) group by (case when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end)
md5=5fb53f95535b7c286ff2d9b05988af74
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select (case when (month(`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end) AS `period`,count(`trn_request_order_head`.`no_request_order`) AS `jumlah` from `trn_request_order_head` where (year(`trn_request_order_head`.`date_trn`) = (select `i_accounting_period`.`year` from `i_accounting_period`)) group by (case when (month(`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end)
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select (case when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end) AS `period`,count(`ideaccounting_dev`.`trn_request_order_head`.`no_request_order`) AS `jumlah` from `ideaccounting_dev`.`trn_request_order_head` where (year(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = (select `ideaccounting_dev`.`i_accounting_period`.`year` from `ideaccounting_dev`.`i_accounting_period`)) group by (case when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 1) then \'Januari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 2) then \'Februari\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 3) then \'Maret\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 4) then \'April\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 5) then \'Mei\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 6) then \'Juni\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 7) then \'Juli\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 8) then \'Agustus\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 9) then \'September\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 10) then \'Oktober\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 11) then \'November\' when (month(`ideaccounting_dev`.`trn_request_order_head`.`date_trn`) = 12) then \'Desember\' else \'\' end)
