TYPE=VIEW
query=select `ideaccounting_dev`.`mst_service`.`service_name` AS `service_name`,`ideaccounting_dev`.`trn_service_det`.`no_service` AS `no_service`,`ideaccounting_dev`.`trn_service_det`.`number_asc` AS `number_asc`,`ideaccounting_dev`.`trn_service_det`.`notes` AS `notes_det`,`ideaccounting_dev`.`trn_service_det`.`qty` AS `qty`,`ideaccounting_dev`.`trn_service_det`.`price` AS `price`,`ideaccounting_dev`.`trn_service_det`.`nominal` AS `nominal`,`ideaccounting_dev`.`trn_service_head`.`date_trn` AS `date_trn`,`ideaccounting_dev`.`mst_employee`.`first_name` AS `first_name`,`ideaccounting_dev`.`mst_employee`.`last_name` AS `last_name`,`ideaccounting_dev`.`mst_customer`.`first_name` AS `first_name2`,`ideaccounting_dev`.`mst_customer`.`last_name` AS `last_name2`,`ideaccounting_dev`.`trn_service_head`.`notes` AS `notes` from ((((`ideaccounting_dev`.`trn_service_det` join `ideaccounting_dev`.`mst_service` on((`ideaccounting_dev`.`trn_service_det`.`id_service` = `ideaccounting_dev`.`mst_service`.`id_service`))) join `ideaccounting_dev`.`trn_service_head` on((`ideaccounting_dev`.`trn_service_det`.`no_service` = `ideaccounting_dev`.`trn_service_head`.`no_service`))) join `ideaccounting_dev`.`mst_employee` on((`ideaccounting_dev`.`trn_service_det`.`id_employee` = `ideaccounting_dev`.`mst_employee`.`id_employee`))) join `ideaccounting_dev`.`mst_customer` on((`ideaccounting_dev`.`trn_service_head`.`id_customer` = `ideaccounting_dev`.`mst_customer`.`id_customer`)))
md5=7385758c2d4adaf24f1846d9a19c73a5
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select `mst_service`.`service_name` AS `service_name`,`trn_service_det`.`no_service` AS `no_service`,`trn_service_det`.`number_asc` AS `number_asc`,`trn_service_det`.`notes` AS `notes_det`,`trn_service_det`.`qty` AS `qty`,`trn_service_det`.`price` AS `price`,`trn_service_det`.`nominal` AS `nominal`,`trn_service_head`.`date_trn` AS `date_trn`,`mst_employee`.`first_name` AS `first_name`,`mst_employee`.`last_name` AS `last_name`,`mst_customer`.`first_name` AS `first_name2`,`mst_customer`.`last_name` AS `last_name2`,`trn_service_head`.`notes` AS `notes` from ((((`trn_service_det` join `mst_service` on((`trn_service_det`.`id_service` = `mst_service`.`id_service`))) join `trn_service_head` on((`trn_service_det`.`no_service` = `trn_service_head`.`no_service`))) join `mst_employee` on((`trn_service_det`.`id_employee` = `mst_employee`.`id_employee`))) join `mst_customer` on((`trn_service_head`.`id_customer` = `mst_customer`.`id_customer`)))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `ideaccounting_dev`.`mst_service`.`service_name` AS `service_name`,`ideaccounting_dev`.`trn_service_det`.`no_service` AS `no_service`,`ideaccounting_dev`.`trn_service_det`.`number_asc` AS `number_asc`,`ideaccounting_dev`.`trn_service_det`.`notes` AS `notes_det`,`ideaccounting_dev`.`trn_service_det`.`qty` AS `qty`,`ideaccounting_dev`.`trn_service_det`.`price` AS `price`,`ideaccounting_dev`.`trn_service_det`.`nominal` AS `nominal`,`ideaccounting_dev`.`trn_service_head`.`date_trn` AS `date_trn`,`ideaccounting_dev`.`mst_employee`.`first_name` AS `first_name`,`ideaccounting_dev`.`mst_employee`.`last_name` AS `last_name`,`ideaccounting_dev`.`mst_customer`.`first_name` AS `first_name2`,`ideaccounting_dev`.`mst_customer`.`last_name` AS `last_name2`,`ideaccounting_dev`.`trn_service_head`.`notes` AS `notes` from ((((`ideaccounting_dev`.`trn_service_det` join `ideaccounting_dev`.`mst_service` on((`ideaccounting_dev`.`trn_service_det`.`id_service` = `ideaccounting_dev`.`mst_service`.`id_service`))) join `ideaccounting_dev`.`trn_service_head` on((`ideaccounting_dev`.`trn_service_det`.`no_service` = `ideaccounting_dev`.`trn_service_head`.`no_service`))) join `ideaccounting_dev`.`mst_employee` on((`ideaccounting_dev`.`trn_service_det`.`id_employee` = `ideaccounting_dev`.`mst_employee`.`id_employee`))) join `ideaccounting_dev`.`mst_customer` on((`ideaccounting_dev`.`trn_service_head`.`id_customer` = `ideaccounting_dev`.`mst_customer`.`id_customer`)))
