TYPE=VIEW
query=select `a`.`id_aset` AS `id_aset`,`a`.`nama` AS `nama`,`c`.`department_name` AS `department_name`,`b`.`type` AS `type`,`b`.`rate_penyusutan` AS `rate_penyusutan`,(case when (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) >= (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) then round((((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12),0) when ((`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) < (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) and (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) > 0)) then `get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) else 0 end) AS `penyusutan`,(case when isnull(`a`.`id_coa_aset`) then \'\' else `a`.`id_coa_aset` end) AS `id_coa_aset`,(case when isnull(`a`.`id_coa_penyusutan`) then \'\' else `a`.`id_coa_penyusutan` end) AS `id_coa_penyusutan`,(case when isnull(`a`.`id_coa_akumulasi`) then \'\' else `a`.`id_coa_akumulasi` end) AS `id_coa_akumulasi` from ((`ideaccounting_dev`.`mst_aset` `a` join `ideaccounting_dev`.`mst_golaset` `b` on((`b`.`id_golongan` = `a`.`id_golongan`))) join `ideaccounting_dev`.`mst_department` `c` on((`c`.`department_id` = `a`.`id_department`))) where (not(`a`.`id_aset` in (select `ideaccounting_dev`.`i_aset_depreciation`.`id_aset` from `ideaccounting_dev`.`i_aset_depreciation` where ((`ideaccounting_dev`.`i_aset_depreciation`.`period` = `get_month`()) and (`ideaccounting_dev`.`i_aset_depreciation`.`years` = `get_year`())))))
md5=31735ba49eb1ff9cc51794238dbb2cc8
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select `a`.`id_aset` AS `id_aset`,`a`.`nama` AS `nama`,`c`.`department_name` AS `department_name`,`b`.`type` AS `type`,`b`.`rate_penyusutan` AS `rate_penyusutan`,(case when (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) >= (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) then round((((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12),0) when ((`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) < (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) and (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) > 0)) then `get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) else 0 end) AS `penyusutan`,(case when isnull(`a`.`id_coa_aset`) then \'\' else `a`.`id_coa_aset` end) AS `id_coa_aset`,(case when isnull(`a`.`id_coa_penyusutan`) then \'\' else `a`.`id_coa_penyusutan` end) AS `id_coa_penyusutan`,(case when isnull(`a`.`id_coa_akumulasi`) then \'\' else `a`.`id_coa_akumulasi` end) AS `id_coa_akumulasi` from ((`mst_aset` `a` join `mst_golaset` `b` on((`b`.`id_golongan` = `a`.`id_golongan`))) join `mst_department` `c` on((`c`.`department_id` = `a`.`id_department`))) where (not(`a`.`id_aset` in (select `i_aset_depreciation`.`id_aset` from `i_aset_depreciation` where ((`i_aset_depreciation`.`period` = `get_month`()) and (`i_aset_depreciation`.`years` = `get_year`())))))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`id_aset` AS `id_aset`,`a`.`nama` AS `nama`,`c`.`department_name` AS `department_name`,`b`.`type` AS `type`,`b`.`rate_penyusutan` AS `rate_penyusutan`,(case when (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) >= (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) then round((((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12),0) when ((`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) < (((`a`.`nilai_perolehan` * `b`.`rate_penyusutan`) / 100) / 12)) and (`get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) > 0)) then `get_nilai_buku_aset`(`a`.`id_golongan`,`a`.`nilai_perolehan`,`a`.`tanggal_perolehan`,`b`.`rate_penyusutan`) else 0 end) AS `penyusutan`,(case when isnull(`a`.`id_coa_aset`) then \'\' else `a`.`id_coa_aset` end) AS `id_coa_aset`,(case when isnull(`a`.`id_coa_penyusutan`) then \'\' else `a`.`id_coa_penyusutan` end) AS `id_coa_penyusutan`,(case when isnull(`a`.`id_coa_akumulasi`) then \'\' else `a`.`id_coa_akumulasi` end) AS `id_coa_akumulasi` from ((`ideaccounting_dev`.`mst_aset` `a` join `ideaccounting_dev`.`mst_golaset` `b` on((`b`.`id_golongan` = `a`.`id_golongan`))) join `ideaccounting_dev`.`mst_department` `c` on((`c`.`department_id` = `a`.`id_department`))) where (not(`a`.`id_aset` in (select `ideaccounting_dev`.`i_aset_depreciation`.`id_aset` from `ideaccounting_dev`.`i_aset_depreciation` where ((`ideaccounting_dev`.`i_aset_depreciation`.`period` = `get_month`()) and (`ideaccounting_dev`.`i_aset_depreciation`.`years` = `get_year`())))))
