TYPE=VIEW
query=select `ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NOCM` AS `NOCM`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NAMALENGKAP` AS `NAMALENGKAP`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`JENISPASIEN` AS `JENISPASIEN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`RUANGAN` AS `RUANGAN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NAMAPELAYANAN` AS `NAMAPELAYANAN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NOMINAL` AS `NOMINAL` from `ideaccounting_dev`.`tampunglayanansimrsgrouppasien`
md5=e98cf566bf9de727390c747ec085bcd7
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `tampunglayanansimrsgrouppasien`.`NOCM` AS `NOCM`,`tampunglayanansimrsgrouppasien`.`NAMALENGKAP` AS `NAMALENGKAP`,`tampunglayanansimrsgrouppasien`.`JENISPASIEN` AS `JENISPASIEN`,`tampunglayanansimrsgrouppasien`.`RUANGAN` AS `RUANGAN`,`tampunglayanansimrsgrouppasien`.`NAMAPELAYANAN` AS `NAMAPELAYANAN`,`tampunglayanansimrsgrouppasien`.`NOMINAL` AS `NOMINAL` from `tampunglayanansimrsgrouppasien`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NOCM` AS `NOCM`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NAMALENGKAP` AS `NAMALENGKAP`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`JENISPASIEN` AS `JENISPASIEN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`RUANGAN` AS `RUANGAN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NAMAPELAYANAN` AS `NAMAPELAYANAN`,`ideaccounting_dev`.`tampunglayanansimrsgrouppasien`.`NOMINAL` AS `NOMINAL` from `ideaccounting_dev`.`tampunglayanansimrsgrouppasien`
