TYPE=VIEW
query=select `x`.`id_supplier` AS `id_supplier`,concat((case when isnull(`d`.`first_name`) then \'\' else `d`.`first_name` end),\' \',(case when isnull(`d`.`last_name`) then \'\' else `d`.`last_name` end)) AS `nm_supplier`,`d`.`address` AS `address`,`d`.`city` AS `city`,`d`.`phone1` AS `phone1`,`d`.`phone2` AS `phone2`,`d`.`phone3` AS `phone3`,`x`.`no_purchase` AS `no_purchase`,`x`.`no_purchase_order` AS `no_purchase_order`,`x`.`date_trn` AS `date_trn`,`y`.`id_item` AS `id_item`,`e`.`item_name` AS `item_name`,`y`.`qty` AS `qty`,`y`.`id_unit` AS `id_unit`,`f`.`unit` AS `unit`,`y`.`price` AS `price`,`y`.`nominal` AS `nominal`,`x`.`payment_method` AS `payment_method`,`x`.`payment_term_days` AS `payment_term_days`,`x`.`disc_term_days` AS `disc_term_days`,`x`.`disc_term_nominal` AS `disc_term_nominal`,`x`.`notes` AS `notes`,`x`.`subtotal` AS `subtotal`,`x`.`disc` AS `disc`,`x`.`tax` AS `tax`,`x`.`total` AS `total`,`x`.`freight` AS `freight`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((((`ideaccounting_dev`.`trn_purchase_head` `x` join `ideaccounting_dev`.`trn_purchase_det` `y` on((`y`.`no_purchase` = `x`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `d` on((`d`.`id_supplier` = `x`.`id_supplier`))) join `ideaccounting_dev`.`mst_item` `e` on((`e`.`id_item` = `y`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `y`.`id_unit`)))
md5=587c5c702ed357f4c1e0bb4a052660d1
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:02
create-version=1
source=select `x`.`id_supplier` AS `id_supplier`,concat((case when isnull(`d`.`first_name`) then \'\' else `d`.`first_name` end),\' \',(case when isnull(`d`.`last_name`) then \'\' else `d`.`last_name` end)) AS `nm_supplier`,`d`.`address` AS `address`,`d`.`city` AS `city`,`d`.`phone1` AS `phone1`,`d`.`phone2` AS `phone2`,`d`.`phone3` AS `phone3`,`x`.`no_purchase` AS `no_purchase`,`x`.`no_purchase_order` AS `no_purchase_order`,`x`.`date_trn` AS `date_trn`,`y`.`id_item` AS `id_item`,`e`.`item_name` AS `item_name`,`y`.`qty` AS `qty`,`y`.`id_unit` AS `id_unit`,`f`.`unit` AS `unit`,`y`.`price` AS `price`,`y`.`nominal` AS `nominal`,`x`.`payment_method` AS `payment_method`,`x`.`payment_term_days` AS `payment_term_days`,`x`.`disc_term_days` AS `disc_term_days`,`x`.`disc_term_nominal` AS `disc_term_nominal`,`x`.`notes` AS `notes`,`x`.`subtotal` AS `subtotal`,`x`.`disc` AS `disc`,`x`.`tax` AS `tax`,`x`.`total` AS `total`,`x`.`freight` AS `freight`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from ((((`trn_purchase_head` `x` join `trn_purchase_det` `y` on((`y`.`no_purchase` = `x`.`no_purchase`))) join `mst_supplier` `d` on((`d`.`id_supplier` = `x`.`id_supplier`))) join `mst_item` `e` on((`e`.`id_item` = `y`.`id_item`))) join `mst_unit` `f` on((`f`.`id_unit` = `y`.`id_unit`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `x`.`id_supplier` AS `id_supplier`,concat((case when isnull(`d`.`first_name`) then \'\' else `d`.`first_name` end),\' \',(case when isnull(`d`.`last_name`) then \'\' else `d`.`last_name` end)) AS `nm_supplier`,`d`.`address` AS `address`,`d`.`city` AS `city`,`d`.`phone1` AS `phone1`,`d`.`phone2` AS `phone2`,`d`.`phone3` AS `phone3`,`x`.`no_purchase` AS `no_purchase`,`x`.`no_purchase_order` AS `no_purchase_order`,`x`.`date_trn` AS `date_trn`,`y`.`id_item` AS `id_item`,`e`.`item_name` AS `item_name`,`y`.`qty` AS `qty`,`y`.`id_unit` AS `id_unit`,`f`.`unit` AS `unit`,`y`.`price` AS `price`,`y`.`nominal` AS `nominal`,`x`.`payment_method` AS `payment_method`,`x`.`payment_term_days` AS `payment_term_days`,`x`.`disc_term_days` AS `disc_term_days`,`x`.`disc_term_nominal` AS `disc_term_nominal`,`x`.`notes` AS `notes`,`x`.`subtotal` AS `subtotal`,`x`.`disc` AS `disc`,`x`.`tax` AS `tax`,`x`.`total` AS `total`,`x`.`freight` AS `freight`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((((`ideaccounting_dev`.`trn_purchase_head` `x` join `ideaccounting_dev`.`trn_purchase_det` `y` on((`y`.`no_purchase` = `x`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `d` on((`d`.`id_supplier` = `x`.`id_supplier`))) join `ideaccounting_dev`.`mst_item` `e` on((`e`.`id_item` = `y`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `y`.`id_unit`)))
