TYPE=VIEW
query=select `a`.`no_purchase` AS `no_purchase`,cast(`a`.`date_trn` as date) AS `date_trn`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,(case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end) AS `disc_amount`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) <> 0) then ((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else 0 end) AS `balance`,`a`.`notes` AS `notes`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) < 0) then -(((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end))) else 0 end) AS `lebih_bayar` from (`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) order by `a`.`id_supplier`,`a`.`date_trn`
md5=13b8cd958dfd5a205dc5b64aeedcf5f5
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select `a`.`no_purchase` AS `no_purchase`,cast(`a`.`date_trn` as date) AS `date_trn`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,(case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end) AS `disc_amount`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) <> 0) then ((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else 0 end) AS `balance`,`a`.`notes` AS `notes`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) < 0) then -(((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end))) else 0 end) AS `lebih_bayar` from (`ap_status` `a` join `mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) order by `a`.`id_supplier`,`a`.`date_trn`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_purchase` AS `no_purchase`,cast(`a`.`date_trn` as date) AS `date_trn`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,(case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end) AS `disc_amount`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) <> 0) then ((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else 0 end) AS `balance`,`a`.`notes` AS `notes`,(case when (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) < 0) then -(((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end))) else 0 end) AS `lebih_bayar` from (`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) order by `a`.`id_supplier`,`a`.`date_trn`
