TYPE=VIEW
query=select `ideaccounting_dev`.`mst_supplier`.`id_supplier` AS `ID`,concat((case when isnull(`ideaccounting_dev`.`mst_supplier`.`first_name`) then \'\' else `ideaccounting_dev`.`mst_supplier`.`first_name` end),\' \',(case when isnull(`ideaccounting_dev`.`mst_supplier`.`last_name`) then \'\' else `ideaccounting_dev`.`mst_supplier`.`last_name` end)) AS `Nama`,`ideaccounting_dev`.`mst_supplier`.`address` AS `Alamat`,`ideaccounting_dev`.`mst_supplier`.`city` AS `Kota`,`ideaccounting_dev`.`mst_supplier`.`state` AS `Propinsi`,concat(`ideaccounting_dev`.`mst_supplier`.`phone1`,\',\',`ideaccounting_dev`.`mst_supplier`.`phone2`) AS `Telepon`,`ideaccounting_dev`.`mst_supplier`.`email` AS `Email`,`ideaccounting_dev`.`mst_supplier`.`website` AS `Wesite`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from `ideaccounting_dev`.`mst_supplier`
md5=574cd0a1f2cb0170e11609cf4c414574
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:04
create-version=1
source=select `mst_supplier`.`id_supplier` AS `ID`,concat((case when isnull(`mst_supplier`.`first_name`) then \'\' else `mst_supplier`.`first_name` end),\' \',(case when isnull(`mst_supplier`.`last_name`) then \'\' else `mst_supplier`.`last_name` end)) AS `Nama`,`mst_supplier`.`address` AS `Alamat`,`mst_supplier`.`city` AS `Kota`,`mst_supplier`.`state` AS `Propinsi`,concat(`mst_supplier`.`phone1`,\',\',`mst_supplier`.`phone2`) AS `Telepon`,`mst_supplier`.`email` AS `Email`,`mst_supplier`.`website` AS `Wesite`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from `mst_supplier`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `ideaccounting_dev`.`mst_supplier`.`id_supplier` AS `ID`,concat((case when isnull(`ideaccounting_dev`.`mst_supplier`.`first_name`) then \'\' else `ideaccounting_dev`.`mst_supplier`.`first_name` end),\' \',(case when isnull(`ideaccounting_dev`.`mst_supplier`.`last_name`) then \'\' else `ideaccounting_dev`.`mst_supplier`.`last_name` end)) AS `Nama`,`ideaccounting_dev`.`mst_supplier`.`address` AS `Alamat`,`ideaccounting_dev`.`mst_supplier`.`city` AS `Kota`,`ideaccounting_dev`.`mst_supplier`.`state` AS `Propinsi`,concat(`ideaccounting_dev`.`mst_supplier`.`phone1`,\',\',`ideaccounting_dev`.`mst_supplier`.`phone2`) AS `Telepon`,`ideaccounting_dev`.`mst_supplier`.`email` AS `Email`,`ideaccounting_dev`.`mst_supplier`.`website` AS `Wesite`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from `ideaccounting_dev`.`mst_supplier`
