TYPE=VIEW
query=select `a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_purchase_order` AS `no_purchase_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,`a`.`total` AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,`c`.`price` AS `price`,(`c`.`qty` * `c`.`price`) AS `total`,`a`.`freight` AS `freight` from (((`ideaccounting_dev`.`trn_purchase_order_head` `a` join `ideaccounting_dev`.`mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) join `ideaccounting_dev`.`trn_purchase_order_det` `c` on((`c`.`no_purchase_order` = `a`.`no_purchase_order`))) join `ideaccounting_dev`.`mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) order by `c`.`number_asc`
md5=c43d17642ee90ee23fc7e8f9601cf0cc
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:06
create-version=1
source=select `a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_purchase_order` AS `no_purchase_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,`a`.`total` AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,`c`.`price` AS `price`,(`c`.`qty` * `c`.`price`) AS `total`,`a`.`freight` AS `freight` from (((`trn_purchase_order_head` `a` join `mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) join `trn_purchase_order_det` `c` on((`c`.`no_purchase_order` = `a`.`no_purchase_order`))) join `mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) order by `c`.`number_asc`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_purchase_order` AS `no_purchase_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,`a`.`total` AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,`c`.`price` AS `price`,(`c`.`qty` * `c`.`price`) AS `total`,`a`.`freight` AS `freight` from (((`ideaccounting_dev`.`trn_purchase_order_head` `a` join `ideaccounting_dev`.`mst_supplier` `b` on((`b`.`id_supplier` = `a`.`id_supplier`))) join `ideaccounting_dev`.`trn_purchase_order_det` `c` on((`c`.`no_purchase_order` = `a`.`no_purchase_order`))) join `ideaccounting_dev`.`mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) order by `c`.`number_asc`
