TYPE=VIEW
query=select distinct `a`.`no_sales` AS `no_sales`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`date_trn` AS `date_trn`,(((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) AS `total_ar`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`termpaydisc` AS `termpaydisc`,cast((`a`.`date_trn` + interval `b`.`termpaydisc` day) as date) AS `jatuh_tempo`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`g`.`id_curr` AS `id_curr` from (((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`trn_sales_det` `g` on((`g`.`no_sales` = `b`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
md5=02acb1b6a7cea557ae24fce2a522b4fb
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:06
create-version=1
source=select distinct `a`.`no_sales` AS `no_sales`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`date_trn` AS `date_trn`,(((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) AS `total_ar`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`termpaydisc` AS `termpaydisc`,cast((`a`.`date_trn` + interval `b`.`termpaydisc` day) as date) AS `jatuh_tempo`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,`g`.`id_curr` AS `id_curr` from (((`ar_status` `a` join `trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `trn_sales_det` `g` on((`g`.`no_sales` = `b`.`no_sales`))) join `mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select distinct `a`.`no_sales` AS `no_sales`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`date_trn` AS `date_trn`,(((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) AS `total_ar`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`termpaydisc` AS `termpaydisc`,cast((`a`.`date_trn` + interval `b`.`termpaydisc` day) as date) AS `jatuh_tempo`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`g`.`id_curr` AS `id_curr` from (((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`trn_sales_det` `g` on((`g`.`no_sales` = `b`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (((((case when isnull(`a`.`sales_amount`) then 0 else `a`.`sales_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
