TYPE=VIEW
query=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`b`.`parent` AS `parent`,(case when isnull(`c`.`account_name`) then (select `ideaccounting_dev`.`i_project_name`.`profit_notes` from `ideaccounting_dev`.`i_project_name`) else `c`.`account_name` end) AS `account_parent`,(case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) AS `saldo`,(case when (`b`.`golongan` = 1) then \'ASET\' when (`b`.`golongan` = 2) then \'KEWAJIBAN\' when (`b`.`golongan` = 3) then \'EKUITAS\' when isnull(`b`.`golongan`) then \'EKUITAS\' end) AS `golongan`,(case when isnull(`b`.`golongan`) then 3 else `b`.`golongan` end) AS `id_golongan`,(case when isnull(`c`.`parent`) then \'999999\' else `c`.`parent` end) AS `id_parent2`,(case when isnull(`d`.`account_name`) then (select `ideaccounting_dev`.`i_project_name`.`profit_notes_header` from `ideaccounting_dev`.`i_project_name`) else `d`.`account_name` end) AS `parent2`,(select (case when isnull(`ideaccounting_dev`.`i_project_name`.`header_text`) then \'\' else `ideaccounting_dev`.`i_project_name`.`header_text` end) AS `header_text` from `ideaccounting_dev`.`i_project_name` where (`ideaccounting_dev`.`i_project_name`.`project_default` = 1)) AS `header_text`,(select sum(`ideaccounting_dev`.`temp_pasiva`.`saldo`) from `ideaccounting_dev`.`temp_pasiva`) AS `total_pasiva`,(select sum(`ideaccounting_dev`.`temp_pasiva_tahunlalu`.`saldo`) from `ideaccounting_dev`.`temp_pasiva_tahunlalu`) AS `total_pasiva_lalu`,(select sum(`ideaccounting_dev`.`temp_aktiva`.`saldo`) from `ideaccounting_dev`.`temp_aktiva`) AS `total_aktiva` from (((`ideaccounting_dev`.`temp_aktiva` `a` left join `ideaccounting_dev`.`mst_account` `b` on((`b`.`id_account` = `a`.`id_account`))) left join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `b`.`parent`))) left join `ideaccounting_dev`.`mst_account` `d` on((`d`.`id_account` = `c`.`parent`))) where ((case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) > 0) order by `a`.`id_account`
md5=ca7ca536179ee73331cc6df9a97fc319
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`b`.`parent` AS `parent`,(case when isnull(`c`.`account_name`) then (select `i_project_name`.`profit_notes` from `i_project_name`) else `c`.`account_name` end) AS `account_parent`,(case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) AS `saldo`,(case when (`b`.`golongan` = 1) then \'ASET\' when (`b`.`golongan` = 2) then \'KEWAJIBAN\' when (`b`.`golongan` = 3) then \'EKUITAS\' when isnull(`b`.`golongan`) then \'EKUITAS\' end) AS `golongan`,(case when isnull(`b`.`golongan`) then 3 else `b`.`golongan` end) AS `id_golongan`,(case when isnull(`c`.`parent`) then \'999999\' else `c`.`parent` end) AS `id_parent2`,(case when isnull(`d`.`account_name`) then (select `i_project_name`.`profit_notes_header` from `i_project_name`) else `d`.`account_name` end) AS `parent2`,(select (case when isnull(`i_project_name`.`header_text`) then \'\' else `i_project_name`.`header_text` end) AS `header_text` from `i_project_name` where (`i_project_name`.`project_default` = 1)) AS `header_text`,(select sum(`temp_pasiva`.`saldo`) from `temp_pasiva`) AS `total_pasiva`,(select sum(`temp_pasiva_tahunlalu`.`saldo`) from `temp_pasiva_tahunlalu`) AS `total_pasiva_lalu`,(select sum(`temp_aktiva`.`saldo`) from `temp_aktiva`) AS `total_aktiva` from (((`temp_aktiva` `a` left join `mst_account` `b` on((`b`.`id_account` = `a`.`id_account`))) left join `mst_account` `c` on((`c`.`id_account` = `b`.`parent`))) left join `mst_account` `d` on((`d`.`id_account` = `c`.`parent`))) where ((case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) > 0) order by `a`.`id_account`
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`id_account` AS `id_account`,`a`.`account_name` AS `account_name`,`b`.`parent` AS `parent`,(case when isnull(`c`.`account_name`) then (select `ideaccounting_dev`.`i_project_name`.`profit_notes` from `ideaccounting_dev`.`i_project_name`) else `c`.`account_name` end) AS `account_parent`,(case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) AS `saldo`,(case when (`b`.`golongan` = 1) then \'ASET\' when (`b`.`golongan` = 2) then \'KEWAJIBAN\' when (`b`.`golongan` = 3) then \'EKUITAS\' when isnull(`b`.`golongan`) then \'EKUITAS\' end) AS `golongan`,(case when isnull(`b`.`golongan`) then 3 else `b`.`golongan` end) AS `id_golongan`,(case when isnull(`c`.`parent`) then \'999999\' else `c`.`parent` end) AS `id_parent2`,(case when isnull(`d`.`account_name`) then (select `ideaccounting_dev`.`i_project_name`.`profit_notes_header` from `ideaccounting_dev`.`i_project_name`) else `d`.`account_name` end) AS `parent2`,(select (case when isnull(`ideaccounting_dev`.`i_project_name`.`header_text`) then \'\' else `ideaccounting_dev`.`i_project_name`.`header_text` end) AS `header_text` from `ideaccounting_dev`.`i_project_name` where (`ideaccounting_dev`.`i_project_name`.`project_default` = 1)) AS `header_text`,(select sum(`ideaccounting_dev`.`temp_pasiva`.`saldo`) from `ideaccounting_dev`.`temp_pasiva`) AS `total_pasiva`,(select sum(`ideaccounting_dev`.`temp_pasiva_tahunlalu`.`saldo`) from `ideaccounting_dev`.`temp_pasiva_tahunlalu`) AS `total_pasiva_lalu`,(select sum(`ideaccounting_dev`.`temp_aktiva`.`saldo`) from `ideaccounting_dev`.`temp_aktiva`) AS `total_aktiva` from (((`ideaccounting_dev`.`temp_aktiva` `a` left join `ideaccounting_dev`.`mst_account` `b` on((`b`.`id_account` = `a`.`id_account`))) left join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `b`.`parent`))) left join `ideaccounting_dev`.`mst_account` `d` on((`d`.`id_account` = `c`.`parent`))) where ((case when isnull(`a`.`saldo`) then 0 else `a`.`saldo` end) > 0) order by `a`.`id_account`
