TYPE=VIEW
query=select `ideaccounting_dev`.`mst_item`.`id_item` AS `id_item`,`ideaccounting_dev`.`mst_item`.`item_name` AS `item_name`,`ideaccounting_dev`.`mst_item`.`id_category` AS `id_category`,`ideaccounting_dev`.`mst_item`.`id_jenis` AS `id_jenis`,`ideaccounting_dev`.`mst_item`.`id_account` AS `id_account`,`ideaccounting_dev`.`mst_item`.`main_unit` AS `main_unit`,`ideaccounting_dev`.`mst_item`.`buy_unit` AS `buy_unit`,`ideaccounting_dev`.`mst_item`.`sell_unit` AS `sell_unit`,`ideaccounting_dev`.`mst_item`.`flag_buy` AS `flag_buy`,`ideaccounting_dev`.`mst_item`.`flag_sell` AS `flag_sell`,`ideaccounting_dev`.`mst_item`.`flag_inv` AS `flag_inv`,`ideaccounting_dev`.`mst_item`.`blob_image` AS `blob_image`,`ideaccounting_dev`.`mst_item`.`sell_price` AS `sell_price`,`ideaccounting_dev`.`mst_item`.`modified_user` AS `modified_user`,`ideaccounting_dev`.`mst_item`.`created_date` AS `created_date`,`ideaccounting_dev`.`mst_item`.`modified_date` AS `modified_date`,`ideaccounting_dev`.`mst_item`.`created_user` AS `created_user`,`ideaccounting_dev`.`mst_item`.`id_warehouse` AS `id_warehouse`,`ideaccounting_dev`.`mst_item`.`max_qty` AS `max_qty`,`ideaccounting_dev`.`mst_item`.`min_qty` AS `min_qty`,`ideaccounting_dev`.`mst_item`.`notes` AS `notes`,`ideaccounting_dev`.`mst_item`.`length` AS `length`,`ideaccounting_dev`.`mst_item`.`width` AS `width`,`ideaccounting_dev`.`mst_item`.`height` AS `height`,`ideaccounting_dev`.`mst_item`.`weight` AS `weight`,(case when isnull(`ideaccounting_dev`.`mst_item`.`id_barcode`) then \'\' else `ideaccounting_dev`.`mst_item`.`id_barcode` end) AS `id_barcode` from `ideaccounting_dev`.`mst_item` where (((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_buy`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_buy` end) = 1) or ((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_inv`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_inv` end) = 1))
md5=5e1fc64e03c27cdcc6bae223358eb233
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `mst_item`.`id_item` AS `id_item`,`mst_item`.`item_name` AS `item_name`,`mst_item`.`id_category` AS `id_category`,`mst_item`.`id_jenis` AS `id_jenis`,`mst_item`.`id_account` AS `id_account`,`mst_item`.`main_unit` AS `main_unit`,`mst_item`.`buy_unit` AS `buy_unit`,`mst_item`.`sell_unit` AS `sell_unit`,`mst_item`.`flag_buy` AS `flag_buy`,`mst_item`.`flag_sell` AS `flag_sell`,`mst_item`.`flag_inv` AS `flag_inv`,`mst_item`.`blob_image` AS `blob_image`,`mst_item`.`sell_price` AS `sell_price`,`mst_item`.`modified_user` AS `modified_user`,`mst_item`.`created_date` AS `created_date`,`mst_item`.`modified_date` AS `modified_date`,`mst_item`.`created_user` AS `created_user`,`mst_item`.`id_warehouse` AS `id_warehouse`,`mst_item`.`max_qty` AS `max_qty`,`mst_item`.`min_qty` AS `min_qty`,`mst_item`.`notes` AS `notes`,`mst_item`.`length` AS `length`,`mst_item`.`width` AS `width`,`mst_item`.`height` AS `height`,`mst_item`.`weight` AS `weight`,(case when isnull(`mst_item`.`id_barcode`) then \'\' else `mst_item`.`id_barcode` end) AS `id_barcode` from `mst_item` where (((case when isnull(`mst_item`.`flag_buy`) then 0 else `mst_item`.`flag_buy` end) = 1) or ((case when isnull(`mst_item`.`flag_inv`) then 0 else `mst_item`.`flag_inv` end) = 1))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `ideaccounting_dev`.`mst_item`.`id_item` AS `id_item`,`ideaccounting_dev`.`mst_item`.`item_name` AS `item_name`,`ideaccounting_dev`.`mst_item`.`id_category` AS `id_category`,`ideaccounting_dev`.`mst_item`.`id_jenis` AS `id_jenis`,`ideaccounting_dev`.`mst_item`.`id_account` AS `id_account`,`ideaccounting_dev`.`mst_item`.`main_unit` AS `main_unit`,`ideaccounting_dev`.`mst_item`.`buy_unit` AS `buy_unit`,`ideaccounting_dev`.`mst_item`.`sell_unit` AS `sell_unit`,`ideaccounting_dev`.`mst_item`.`flag_buy` AS `flag_buy`,`ideaccounting_dev`.`mst_item`.`flag_sell` AS `flag_sell`,`ideaccounting_dev`.`mst_item`.`flag_inv` AS `flag_inv`,`ideaccounting_dev`.`mst_item`.`blob_image` AS `blob_image`,`ideaccounting_dev`.`mst_item`.`sell_price` AS `sell_price`,`ideaccounting_dev`.`mst_item`.`modified_user` AS `modified_user`,`ideaccounting_dev`.`mst_item`.`created_date` AS `created_date`,`ideaccounting_dev`.`mst_item`.`modified_date` AS `modified_date`,`ideaccounting_dev`.`mst_item`.`created_user` AS `created_user`,`ideaccounting_dev`.`mst_item`.`id_warehouse` AS `id_warehouse`,`ideaccounting_dev`.`mst_item`.`max_qty` AS `max_qty`,`ideaccounting_dev`.`mst_item`.`min_qty` AS `min_qty`,`ideaccounting_dev`.`mst_item`.`notes` AS `notes`,`ideaccounting_dev`.`mst_item`.`length` AS `length`,`ideaccounting_dev`.`mst_item`.`width` AS `width`,`ideaccounting_dev`.`mst_item`.`height` AS `height`,`ideaccounting_dev`.`mst_item`.`weight` AS `weight`,(case when isnull(`ideaccounting_dev`.`mst_item`.`id_barcode`) then \'\' else `ideaccounting_dev`.`mst_item`.`id_barcode` end) AS `id_barcode` from `ideaccounting_dev`.`mst_item` where (((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_buy`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_buy` end) = 1) or ((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_inv`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_inv` end) = 1))
