TYPE=VIEW
query=select distinct `a`.`no_purchase` AS `no_purchase`,`a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier`,`a`.`date_trn` AS `date_trn`,((`a`.`purchase_amount` - `a`.`return_amount`) - `a`.`disc_amount`) AS `total_ap`,`a`.`paid_amount` AS `paid_amount`,((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`payment_term_days` AS `payment_term_days`,cast((`a`.`date_trn` + interval `b`.`payment_term_days` day) as date) AS `jatuh_tempo`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`b`.`kurs` AS `kurs`,`h`.`id_curr` AS `id_curr`,`k`.`convert_value` AS `convert_value` from ((((`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`trn_purchase_det` `h` on((`h`.`no_purchase` = `b`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `ideaccounting_dev`.`mst_setcurrency` `k` on((`k`.`id_currency` = `h`.`id_curr`))) where (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
md5=47d663811190e8e7fcd31c057946bd44
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:04
create-version=1
source=select distinct `a`.`no_purchase` AS `no_purchase`,`a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier`,`a`.`date_trn` AS `date_trn`,((`a`.`purchase_amount` - `a`.`return_amount`) - `a`.`disc_amount`) AS `total_ap`,`a`.`paid_amount` AS `paid_amount`,((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`payment_term_days` AS `payment_term_days`,cast((`a`.`date_trn` + interval `b`.`payment_term_days` day) as date) AS `jatuh_tempo`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,`b`.`kurs` AS `kurs`,`h`.`id_curr` AS `id_curr`,`k`.`convert_value` AS `convert_value` from ((((`ap_status` `a` join `trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `trn_purchase_det` `h` on((`h`.`no_purchase` = `b`.`no_purchase`))) join `mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `mst_setcurrency` `k` on((`k`.`id_currency` = `h`.`id_curr`))) where (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select distinct `a`.`no_purchase` AS `no_purchase`,`a`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier`,`a`.`date_trn` AS `date_trn`,((`a`.`purchase_amount` - `a`.`return_amount`) - `a`.`disc_amount`) AS `total_ap`,`a`.`paid_amount` AS `paid_amount`,((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) AS `balance`,`b`.`payment_term_days` AS `payment_term_days`,cast((`a`.`date_trn` + interval `b`.`payment_term_days` day) as date) AS `jatuh_tempo`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`b`.`kurs` AS `kurs`,`h`.`id_curr` AS `id_curr`,`k`.`convert_value` AS `convert_value` from ((((`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`trn_purchase_det` `h` on((`h`.`no_purchase` = `b`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `ideaccounting_dev`.`mst_setcurrency` `k` on((`k`.`id_currency` = `h`.`id_curr`))) where (((((case when isnull(`a`.`purchase_amount`) then 0 else `a`.`purchase_amount` end) - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`disc_amount`) then 0 else `a`.`disc_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) > 0)
