TYPE=VIEW
query=select `a`.`no_sales` AS `no_sales`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`sales_amount` AS `sales_amount`,`a`.`return_amount` AS `return_amount`,(`a`.`sales_amount` - `a`.`return_amount`) AS `nett_sales`,`b`.`no_payment_ar` AS `no_payment_ar`,`d`.`date_trn` AS `date_trn`,`a`.`disc_amount` AS `disc_amount`,`b`.`paid_amount` AS `paid_amount`,`d`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`d`.`id_currency` AS `id_currency` from (((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_payment_ar_det` `b` on((`b`.`no_invoice` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`))) join `ideaccounting_dev`.`trn_payment_ar_head` `d` on((`d`.`no_payment_ar` = `b`.`no_payment_ar`))) where (`a`.`balance` = 0)
md5=c9bdb7177d67c86795c2e651d4e7b815
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_sales` AS `no_sales`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`sales_amount` AS `sales_amount`,`a`.`return_amount` AS `return_amount`,(`a`.`sales_amount` - `a`.`return_amount`) AS `nett_sales`,`b`.`no_payment_ar` AS `no_payment_ar`,`d`.`date_trn` AS `date_trn`,`a`.`disc_amount` AS `disc_amount`,`b`.`paid_amount` AS `paid_amount`,`d`.`notes` AS `notes`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`d`.`id_currency` AS `id_currency` from (((`ar_status` `a` join `trn_payment_ar_det` `b` on((`b`.`no_invoice` = `a`.`no_sales`))) join `mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`))) join `trn_payment_ar_head` `d` on((`d`.`no_payment_ar` = `b`.`no_payment_ar`))) where (`a`.`balance` = 0)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_sales` AS `no_sales`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer`,`a`.`sales_amount` AS `sales_amount`,`a`.`return_amount` AS `return_amount`,(`a`.`sales_amount` - `a`.`return_amount`) AS `nett_sales`,`b`.`no_payment_ar` AS `no_payment_ar`,`d`.`date_trn` AS `date_trn`,`a`.`disc_amount` AS `disc_amount`,`b`.`paid_amount` AS `paid_amount`,`d`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`d`.`id_currency` AS `id_currency` from (((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_payment_ar_det` `b` on((`b`.`no_invoice` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`))) join `ideaccounting_dev`.`trn_payment_ar_head` `d` on((`d`.`no_payment_ar` = `b`.`no_payment_ar`))) where (`a`.`balance` = 0)
