TYPE=VIEW
query=select `a`.`no_sales` AS `no_sales`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`b`.`notes` AS `notes`,`b`.`term` AS `term`,`a`.`sales_amount` AS `sales_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_customer` AS `id_customer`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then ((`b`.`discpay` * `a`.`sales_amount`) / 100) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then (((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - ((`b`.`discpay` * `a`.`sales_amount`) / 100)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `ideaccounting_dev`.`mst_currency`.`id_currency` from `ideaccounting_dev`.`mst_currency` where (`ideaccounting_dev`.`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (`b`.`payment_method` = 2)
md5=a975c12de30dc6bb8b882d23b0fa0fab
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_sales` AS `no_sales`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`b`.`notes` AS `notes`,`b`.`term` AS `term`,`a`.`sales_amount` AS `sales_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_customer` AS `id_customer`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then ((`b`.`discpay` * `a`.`sales_amount`) / 100) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then (((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - ((`b`.`discpay` * `a`.`sales_amount`) / 100)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `mst_currency`.`id_currency` from `mst_currency` where (`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ar_status` `a` join `trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (`b`.`payment_method` = 2)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_sales` AS `no_sales`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`b`.`notes` AS `notes`,`b`.`term` AS `term`,`a`.`sales_amount` AS `sales_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_customer` AS `id_customer`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then ((`b`.`discpay` * `a`.`sales_amount`) / 100) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`termpaydisc`) then (((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - ((`b`.`discpay` * `a`.`sales_amount`) / 100)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`sales_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `ideaccounting_dev`.`mst_currency`.`id_currency` from `ideaccounting_dev`.`mst_currency` where (`ideaccounting_dev`.`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ideaccounting_dev`.`ar_status` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) where (`b`.`payment_method` = 2)
