TYPE=VIEW
query=select `aph`.`no_payment_ar` AS `no_payment_ar`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `customer_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_customer` AS `id_customer`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_invoice` AS `no_invoice`,`apd`.`invoice_date` AS `invoice_date`,(`apd`.`ap_amount` / `apd`.`kurs`) AS `ap_amount`,(`apd`.`discount` / `apd`.`kurs`) AS `discount`,(`apd`.`ap_amount_net` / `apd`.`kurs`) AS `ap_amount_net`,(`apd`.`paid_amount` / `apd`.`kurs`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,(`apd`.`ap_return` / `apd`.`kurs`) AS `ap_return`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`aph`.`id_currency` AS `id_currency`,`apd`.`kurs` AS `kurs` from (((`ideaccounting_dev`.`trn_payment_ar_head` `aph` join `ideaccounting_dev`.`trn_payment_ar_det` `apd` on((`aph`.`no_payment_ar` = `apd`.`no_payment_ar`))) join `ideaccounting_dev`.`mst_customer` `ms` on((`ms`.`id_customer` = `aph`.`id_customer`))) join `ideaccounting_dev`.`mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`)))
md5=3681777f58300919a2ba3583ff74ed8b
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:04
create-version=1
source=select `aph`.`no_payment_ar` AS `no_payment_ar`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `customer_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_customer` AS `id_customer`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_invoice` AS `no_invoice`,`apd`.`invoice_date` AS `invoice_date`,(`apd`.`ap_amount` / `apd`.`kurs`) AS `ap_amount`,(`apd`.`discount` / `apd`.`kurs`) AS `discount`,(`apd`.`ap_amount_net` / `apd`.`kurs`) AS `ap_amount_net`,(`apd`.`paid_amount` / `apd`.`kurs`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,(`apd`.`ap_return` / `apd`.`kurs`) AS `ap_return`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`aph`.`id_currency` AS `id_currency`,`apd`.`kurs` AS `kurs` from (((`trn_payment_ar_head` `aph` join `trn_payment_ar_det` `apd` on((`aph`.`no_payment_ar` = `apd`.`no_payment_ar`))) join `mst_customer` `ms` on((`ms`.`id_customer` = `aph`.`id_customer`))) join `mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `aph`.`no_payment_ar` AS `no_payment_ar`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `customer_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_customer` AS `id_customer`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_invoice` AS `no_invoice`,`apd`.`invoice_date` AS `invoice_date`,(`apd`.`ap_amount` / `apd`.`kurs`) AS `ap_amount`,(`apd`.`discount` / `apd`.`kurs`) AS `discount`,(`apd`.`ap_amount_net` / `apd`.`kurs`) AS `ap_amount_net`,(`apd`.`paid_amount` / `apd`.`kurs`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,(`apd`.`ap_return` / `apd`.`kurs`) AS `ap_return`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`aph`.`id_currency` AS `id_currency`,`apd`.`kurs` AS `kurs` from (((`ideaccounting_dev`.`trn_payment_ar_head` `aph` join `ideaccounting_dev`.`trn_payment_ar_det` `apd` on((`aph`.`no_payment_ar` = `apd`.`no_payment_ar`))) join `ideaccounting_dev`.`mst_customer` `ms` on((`ms`.`id_customer` = `aph`.`id_customer`))) join `ideaccounting_dev`.`mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`)))
