TYPE=VIEW
query=select `c`.`id_member` AS `id_member`,`a`.`id_attendance` AS `id_attendance`,(case when isnull(`b`.`event_name`) then \'\' else `b`.`event_name` end) AS `event_name`,`b`.`start_date` AS `start_date`,`b`.`end_date` AS `end_date`,(case when isnull(`c`.`nip_member`) then \'\' else `c`.`nip_member` end) AS `nip_member`,(case when isnull(`c`.`member_name`) then \'\' else `c`.`member_name` end) AS `member_name`,(case when isnull(`c`.`position`) then \'\' else `c`.`position` end) AS `position`,(case when isnull(`c`.`area`) then \'\' else `c`.`area` end) AS `area`,(case when isnull(`c`.`region`) then \'\' else `c`.`region` end) AS `region`,(case when isnull(`a`.`id_attendance`) then \'Tidak Hadir\' else \'Hadir\' end) AS `status_hadir`,(case when isnull(`a`.`attendance_date`) then \'\' else `a`.`attendance_date` end) AS `attendance_date` from ((`ideaccounting_dev`.`mst_event_member` `c` left join `ideaccounting_dev`.`i_event_attendance` `a` on((`a`.`id_member` = `c`.`id_member`))) join `ideaccounting_dev`.`mst_event` `b` on((`b`.`id_event` = `a`.`id_event`)))
md5=396b1d4ab48108bf91b8b0a31a4b8ea9
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:03
create-version=1
source=select `c`.`id_member` AS `id_member`,`a`.`id_attendance` AS `id_attendance`,(case when isnull(`b`.`event_name`) then \'\' else `b`.`event_name` end) AS `event_name`,`b`.`start_date` AS `start_date`,`b`.`end_date` AS `end_date`,(case when isnull(`c`.`nip_member`) then \'\' else `c`.`nip_member` end) AS `nip_member`,(case when isnull(`c`.`member_name`) then \'\' else `c`.`member_name` end) AS `member_name`,(case when isnull(`c`.`position`) then \'\' else `c`.`position` end) AS `position`,(case when isnull(`c`.`area`) then \'\' else `c`.`area` end) AS `area`,(case when isnull(`c`.`region`) then \'\' else `c`.`region` end) AS `region`,(case when isnull(`a`.`id_attendance`) then \'Tidak Hadir\' else \'Hadir\' end) AS `status_hadir`,(case when isnull(`a`.`attendance_date`) then \'\' else `a`.`attendance_date` end) AS `attendance_date` from ((`mst_event_member` `c` left join `i_event_attendance` `a` on((`a`.`id_member` = `c`.`id_member`))) join `mst_event` `b` on((`b`.`id_event` = `a`.`id_event`)))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `c`.`id_member` AS `id_member`,`a`.`id_attendance` AS `id_attendance`,(case when isnull(`b`.`event_name`) then \'\' else `b`.`event_name` end) AS `event_name`,`b`.`start_date` AS `start_date`,`b`.`end_date` AS `end_date`,(case when isnull(`c`.`nip_member`) then \'\' else `c`.`nip_member` end) AS `nip_member`,(case when isnull(`c`.`member_name`) then \'\' else `c`.`member_name` end) AS `member_name`,(case when isnull(`c`.`position`) then \'\' else `c`.`position` end) AS `position`,(case when isnull(`c`.`area`) then \'\' else `c`.`area` end) AS `area`,(case when isnull(`c`.`region`) then \'\' else `c`.`region` end) AS `region`,(case when isnull(`a`.`id_attendance`) then \'Tidak Hadir\' else \'Hadir\' end) AS `status_hadir`,(case when isnull(`a`.`attendance_date`) then \'\' else `a`.`attendance_date` end) AS `attendance_date` from ((`ideaccounting_dev`.`mst_event_member` `c` left join `ideaccounting_dev`.`i_event_attendance` `a` on((`a`.`id_member` = `c`.`id_member`))) join `ideaccounting_dev`.`mst_event` `b` on((`b`.`id_event` = `a`.`id_event`)))
