TYPE=VIEW
query=select `a`.`no_adjust_stock` AS `no_adjust_stock`,`a`.`date_trn` AS `date_trn`,`a`.`id_warehouse` AS `id_warehouse`,`b`.`id_item` AS `id_item`,`v`.`item_name` AS `item_name`,`b`.`negative` AS `negative`,`b`.`positive` AS `positive`,`a`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`z`.`warehouse_name` AS `warehouse_name`,`b`.`notes` AS `notes_det` from (((`ideaccounting_dev`.`trn_adjust_stock_head` `a` join `ideaccounting_dev`.`trn_adjust_stock_det` `b` on((`b`.`no_adjust_stock` = `a`.`no_adjust_stock`))) join `ideaccounting_dev`.`mst_item` `v` on((`v`.`id_item` = `b`.`id_item`))) join `ideaccounting_dev`.`mst_warehouse` `z` on((`z`.`id_warehouse` = `a`.`id_warehouse`)))
md5=1c82feb518ade038d9748c0f42e9fe69
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:02
create-version=1
source=select `a`.`no_adjust_stock` AS `no_adjust_stock`,`a`.`date_trn` AS `date_trn`,`a`.`id_warehouse` AS `id_warehouse`,`b`.`id_item` AS `id_item`,`v`.`item_name` AS `item_name`,`b`.`negative` AS `negative`,`b`.`positive` AS `positive`,`a`.`notes` AS `notes`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`z`.`warehouse_name` AS `warehouse_name`,`b`.`notes` AS `notes_det` from (((`trn_adjust_stock_head` `a` join `trn_adjust_stock_det` `b` on((`b`.`no_adjust_stock` = `a`.`no_adjust_stock`))) join `mst_item` `v` on((`v`.`id_item` = `b`.`id_item`))) join `mst_warehouse` `z` on((`z`.`id_warehouse` = `a`.`id_warehouse`)))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`no_adjust_stock` AS `no_adjust_stock`,`a`.`date_trn` AS `date_trn`,`a`.`id_warehouse` AS `id_warehouse`,`b`.`id_item` AS `id_item`,`v`.`item_name` AS `item_name`,`b`.`negative` AS `negative`,`b`.`positive` AS `positive`,`a`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`z`.`warehouse_name` AS `warehouse_name`,`b`.`notes` AS `notes_det` from (((`ideaccounting_dev`.`trn_adjust_stock_head` `a` join `ideaccounting_dev`.`trn_adjust_stock_det` `b` on((`b`.`no_adjust_stock` = `a`.`no_adjust_stock`))) join `ideaccounting_dev`.`mst_item` `v` on((`v`.`id_item` = `b`.`id_item`))) join `ideaccounting_dev`.`mst_warehouse` `z` on((`z`.`id_warehouse` = `a`.`id_warehouse`)))
