TYPE=VIEW
query=select `a`.`no_purchase` AS `no_purchase`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from (((`ideaccounting_dev`.`trn_purchase_det` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item`,`b`.`id_supplier` order by sum(`a`.`qty`) desc,`b`.`id_supplier`
md5=bbda99f12106c1a4fdb09cd8b10693c9
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_purchase` AS `no_purchase`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from (((`trn_purchase_det` `a` join `trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item`,`b`.`id_supplier` order by sum(`a`.`qty`) desc,`b`.`id_supplier`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_purchase` AS `no_purchase`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_supplier` AS `id_supplier`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from (((`ideaccounting_dev`.`trn_purchase_det` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item`,`b`.`id_supplier` order by sum(`a`.`qty`) desc,`b`.`id_supplier`
