TYPE=VIEW
query=select `ideaccounting_dev`.`mst_employee`.`id_employee` AS `ID`,concat((case when isnull(`ideaccounting_dev`.`mst_employee`.`first_name`) then \'\' else `ideaccounting_dev`.`mst_employee`.`first_name` end),\' \',(case when isnull(`ideaccounting_dev`.`mst_employee`.`last_name`) then \'\' else `ideaccounting_dev`.`mst_employee`.`last_name` end)) AS `Nama`,`ideaccounting_dev`.`mst_employee`.`address` AS `Alamat`,`ideaccounting_dev`.`mst_employee`.`city` AS `Kota`,`ideaccounting_dev`.`mst_employee`.`state` AS `Propinsi`,concat(`ideaccounting_dev`.`mst_employee`.`phone1`,\',\',`ideaccounting_dev`.`mst_employee`.`phone2`) AS `Telepon`,`ideaccounting_dev`.`mst_employee`.`email` AS `Email`,`ideaccounting_dev`.`mst_employee`.`website` AS `Wesite`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from `ideaccounting_dev`.`mst_employee`
md5=d7b11434817a3b047f57a3e35963ba2c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:04
create-version=1
source=select `mst_employee`.`id_employee` AS `ID`,concat((case when isnull(`mst_employee`.`first_name`) then \'\' else `mst_employee`.`first_name` end),\' \',(case when isnull(`mst_employee`.`last_name`) then \'\' else `mst_employee`.`last_name` end)) AS `Nama`,`mst_employee`.`address` AS `Alamat`,`mst_employee`.`city` AS `Kota`,`mst_employee`.`state` AS `Propinsi`,concat(`mst_employee`.`phone1`,\',\',`mst_employee`.`phone2`) AS `Telepon`,`mst_employee`.`email` AS `Email`,`mst_employee`.`website` AS `Wesite`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from `mst_employee`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `ideaccounting_dev`.`mst_employee`.`id_employee` AS `ID`,concat((case when isnull(`ideaccounting_dev`.`mst_employee`.`first_name`) then \'\' else `ideaccounting_dev`.`mst_employee`.`first_name` end),\' \',(case when isnull(`ideaccounting_dev`.`mst_employee`.`last_name`) then \'\' else `ideaccounting_dev`.`mst_employee`.`last_name` end)) AS `Nama`,`ideaccounting_dev`.`mst_employee`.`address` AS `Alamat`,`ideaccounting_dev`.`mst_employee`.`city` AS `Kota`,`ideaccounting_dev`.`mst_employee`.`state` AS `Propinsi`,concat(`ideaccounting_dev`.`mst_employee`.`phone1`,\',\',`ideaccounting_dev`.`mst_employee`.`phone2`) AS `Telepon`,`ideaccounting_dev`.`mst_employee`.`email` AS `Email`,`ideaccounting_dev`.`mst_employee`.`website` AS `Wesite`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from `ideaccounting_dev`.`mst_employee`
