TYPE=VIEW
query=select `a`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`a`.`cashbank_no` AS `cashbank_no`,`a`.`date_trn` AS `date_trn`,`d`.`account_name` AS `namaakundet`,`b`.`notes` AS `ketdetail`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,`a`.`evidence_no` AS `evidence_no`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`amount` AS `amount` from (((`ideaccounting_dev`.`trn_cashbank_head` `a` join `ideaccounting_dev`.`trn_cashbank_det` `b` on((`b`.`cashbank_no` = `a`.`cashbank_no`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `a`.`id_account`))) join `ideaccounting_dev`.`mst_account` `d` on((`d`.`id_account` = `b`.`id_account`))) where (`a`.`flag_trans` = \'KM\')
md5=a6ae8d74cee1495bdfdd16ab9f709f94
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:01
create-version=1
source=select `a`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`a`.`cashbank_no` AS `cashbank_no`,`a`.`date_trn` AS `date_trn`,`d`.`account_name` AS `namaakundet`,`b`.`notes` AS `ketdetail`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,`a`.`evidence_no` AS `evidence_no`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`amount` AS `amount` from (((`trn_cashbank_head` `a` join `trn_cashbank_det` `b` on((`b`.`cashbank_no` = `a`.`cashbank_no`))) join `mst_account` `c` on((`c`.`id_account` = `a`.`id_account`))) join `mst_account` `d` on((`d`.`id_account` = `b`.`id_account`))) where (`a`.`flag_trans` = \'KM\')
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`a`.`cashbank_no` AS `cashbank_no`,`a`.`date_trn` AS `date_trn`,`d`.`account_name` AS `namaakundet`,`b`.`notes` AS `ketdetail`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,`a`.`evidence_no` AS `evidence_no`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`amount` AS `amount` from (((`ideaccounting_dev`.`trn_cashbank_head` `a` join `ideaccounting_dev`.`trn_cashbank_det` `b` on((`b`.`cashbank_no` = `a`.`cashbank_no`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `a`.`id_account`))) join `ideaccounting_dev`.`mst_account` `d` on((`d`.`id_account` = `b`.`id_account`))) where (`a`.`flag_trans` = \'KM\')
