TYPE=VIEW
query=select `a`.`journal_no` AS `journal_no`,`a`.`date_trn` AS `date_trn`,`a`.`description` AS `description`,`a`.`total` AS `total`,`b`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`b`.`notes` AS `notes_det`,(case when (`b`.`amount` > 0) then `b`.`amount` else 0 end) AS `debet`,(case when (`b`.`amount` < 0) then (-(1) * `b`.`amount`) else 0 end) AS `credit`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((`ideaccounting_dev`.`trn_adjustjournal_head` `a` join `ideaccounting_dev`.`trn_adjustjournal_det` `b` on((`b`.`journal_no` = `a`.`journal_no`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `b`.`id_account`)))
md5=a03bf9ce50f9880def63988311da104a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:01
create-version=1
source=select `a`.`journal_no` AS `journal_no`,`a`.`date_trn` AS `date_trn`,`a`.`description` AS `description`,`a`.`total` AS `total`,`b`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`b`.`notes` AS `notes_det`,(case when (`b`.`amount` > 0) then `b`.`amount` else 0 end) AS `debet`,(case when (`b`.`amount` < 0) then (-(1) * `b`.`amount`) else 0 end) AS `credit`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from ((`trn_adjustjournal_head` `a` join `trn_adjustjournal_det` `b` on((`b`.`journal_no` = `a`.`journal_no`))) join `mst_account` `c` on((`c`.`id_account` = `b`.`id_account`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`journal_no` AS `journal_no`,`a`.`date_trn` AS `date_trn`,`a`.`description` AS `description`,`a`.`total` AS `total`,`b`.`id_account` AS `id_account`,`c`.`account_name` AS `account_name`,`b`.`notes` AS `notes_det`,(case when (`b`.`amount` > 0) then `b`.`amount` else 0 end) AS `debet`,(case when (`b`.`amount` < 0) then (-(1) * `b`.`amount`) else 0 end) AS `credit`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((`ideaccounting_dev`.`trn_adjustjournal_head` `a` join `ideaccounting_dev`.`trn_adjustjournal_det` `b` on((`b`.`journal_no` = `a`.`journal_no`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `b`.`id_account`)))
