TYPE=VIEW
query=select `a`.`no_request_order` AS `no_request_order`,`a`.`date_trn` AS `date_trn`,`a`.`notes` AS `notes`,`f`.`id_item` AS `id_item`,`c`.`item_name` AS `item_name`,`f`.`qty` AS `qty`,`f`.`approve_qty` AS `approve_qty`,`f`.`approve_date` AS `approve_date`,`f`.`id_unit` AS `id_unit`,`a`.`id_warehouse` AS `id_warehouse`,`j`.`warehouse_name` AS `warehouse_name`,(case when ((sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) < sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) and (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) > 0)) then \'Approve Sebagian\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = 0) then \'Belum di Approve\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) then \'Sudah di Approve\' end) AS `notes_approve`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name` from (((`ideaccounting_dev`.`trn_request_order_head` `a` join `ideaccounting_dev`.`trn_request_order_det` `f` on((`f`.`no_request_order` = `a`.`no_request_order`))) join `ideaccounting_dev`.`mst_item` `c` on((`c`.`id_item` = `f`.`id_item`))) join `ideaccounting_dev`.`mst_warehouse` `j` on((`j`.`id_warehouse` = `a`.`id_warehouse`))) group by `a`.`no_request_order`,`f`.`id_item`,`c`.`item_name`
md5=86dcaf8856cc52286b5910a1803ac5e8
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:06
create-version=1
source=select `a`.`no_request_order` AS `no_request_order`,`a`.`date_trn` AS `date_trn`,`a`.`notes` AS `notes`,`f`.`id_item` AS `id_item`,`c`.`item_name` AS `item_name`,`f`.`qty` AS `qty`,`f`.`approve_qty` AS `approve_qty`,`f`.`approve_date` AS `approve_date`,`f`.`id_unit` AS `id_unit`,`a`.`id_warehouse` AS `id_warehouse`,`j`.`warehouse_name` AS `warehouse_name`,(case when ((sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) < sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) and (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) > 0)) then \'Approve Sebagian\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = 0) then \'Belum di Approve\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) then \'Sudah di Approve\' end) AS `notes_approve`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name` from (((`trn_request_order_head` `a` join `trn_request_order_det` `f` on((`f`.`no_request_order` = `a`.`no_request_order`))) join `mst_item` `c` on((`c`.`id_item` = `f`.`id_item`))) join `mst_warehouse` `j` on((`j`.`id_warehouse` = `a`.`id_warehouse`))) group by `a`.`no_request_order`,`f`.`id_item`,`c`.`item_name`
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`no_request_order` AS `no_request_order`,`a`.`date_trn` AS `date_trn`,`a`.`notes` AS `notes`,`f`.`id_item` AS `id_item`,`c`.`item_name` AS `item_name`,`f`.`qty` AS `qty`,`f`.`approve_qty` AS `approve_qty`,`f`.`approve_date` AS `approve_date`,`f`.`id_unit` AS `id_unit`,`a`.`id_warehouse` AS `id_warehouse`,`j`.`warehouse_name` AS `warehouse_name`,(case when ((sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) < sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) and (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) > 0)) then \'Approve Sebagian\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = 0) then \'Belum di Approve\' when (sum((case when isnull(`f`.`approve_qty`) then 0 else `f`.`approve_qty` end)) = sum((case when isnull(`f`.`qty`) then 0 else `f`.`qty` end))) then \'Sudah di Approve\' end) AS `notes_approve`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name` from (((`ideaccounting_dev`.`trn_request_order_head` `a` join `ideaccounting_dev`.`trn_request_order_det` `f` on((`f`.`no_request_order` = `a`.`no_request_order`))) join `ideaccounting_dev`.`mst_item` `c` on((`c`.`id_item` = `f`.`id_item`))) join `ideaccounting_dev`.`mst_warehouse` `j` on((`j`.`id_warehouse` = `a`.`id_warehouse`))) group by `a`.`no_request_order`,`f`.`id_item`,`c`.`item_name`
