TYPE=VIEW
query=select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'Material\' AS `Detail` from ((((`ideaccounting_dev`.`mst_bom_head` `a` join `ideaccounting_dev`.`mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `ideaccounting_dev`.`mst_bom_material` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`))) union all select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'WIP\' AS `Detail` from ((((`ideaccounting_dev`.`mst_bom_head` `a` join `ideaccounting_dev`.`mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `ideaccounting_dev`.`mst_bom_wip` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`)))
md5=1506ebb8b221f6fac6312e59d28d6404
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'Material\' AS `Detail` from ((((`mst_bom_head` `a` join `mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `mst_bom_material` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`))) union all select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'WIP\' AS `Detail` from ((((`mst_bom_head` `a` join `mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `mst_bom_wip` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'Material\' AS `Detail` from ((((`ideaccounting_dev`.`mst_bom_head` `a` join `ideaccounting_dev`.`mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `ideaccounting_dev`.`mst_bom_material` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`))) union all select `a`.`no_bom` AS `no_bom`,`a`.`notes` AS `notes`,`a`.`qty_item_production` AS `qty_item_production`,`b`.`unit` AS `unit`,`a`.`date_trn` AS `date_trn`,`a`.`total_cost` AS `total_cost`,`c`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`c`.`qty_material` AS `qty_material`,`f`.`unit` AS `unit_material`,`c`.`cost` AS `cost`,`c`.`total_cost` AS `total_cost_material`,\'WIP\' AS `Detail` from ((((`ideaccounting_dev`.`mst_bom_head` `a` join `ideaccounting_dev`.`mst_unit` `b` on((`b`.`id_unit` = `a`.`id_unit`))) left join `ideaccounting_dev`.`mst_bom_wip` `c` on((`c`.`no_bom` = `a`.`no_bom`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) join `ideaccounting_dev`.`mst_unit` `f` on((`f`.`id_unit` = `c`.`id_unit`)))
