TYPE=VIEW
query=select `hitung_rekap_jual_category`.`id_category` AS `id_category`,sum(`hitung_rekap_jual_category`.`total`) AS `total` from `ideaccounting_dev`.`hitung_rekap_jual_category` group by `hitung_rekap_jual_category`.`id_category`
md5=54e112a382c82a0c3ef1eb6b225d9b8a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `hitung_rekap_jual_category`.`id_category` AS `id_category`,sum(`hitung_rekap_jual_category`.`total`) AS `total` from `hitung_rekap_jual_category` group by `hitung_rekap_jual_category`.`id_category`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `hitung_rekap_jual_category`.`id_category` AS `id_category`,sum(`hitung_rekap_jual_category`.`total`) AS `total` from `ideaccounting_dev`.`hitung_rekap_jual_category` group by `hitung_rekap_jual_category`.`id_category`
