TYPE=VIEW
query=select `aph`.`no_payment_ap` AS `no_payment_ap`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `supplier_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_supplier` AS `id_supplier`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_purchase` AS `no_purchase`,`apd`.`invoice_date` AS `invoice_date`,`apd`.`ap_amount` AS `ap_amount`,`apd`.`discount` AS `discount`,sum(`apd`.`ap_amount_net`) AS `ap_amount_net`,(`cd`.`paid_amount` - `apd`.`paid_amount`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,`apd`.`ap_return` AS `ap_return`,`ms`.`city` AS `city`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`apd`.`paid_amount` AS `pembayaran` from ((((`ideaccounting_dev`.`trn_payment_ap_head` `aph` join `ideaccounting_dev`.`trn_payment_ap_det` `apd` on((`aph`.`no_payment_ap` = `apd`.`no_payment_ap`))) join `ideaccounting_dev`.`ap_status` `cd` on((`cd`.`no_purchase` = `apd`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `ms` on((`ms`.`id_supplier` = `aph`.`id_supplier`))) join `ideaccounting_dev`.`mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`))) group by `apd`.`no_purchase`
md5=ecb44ac7f64257bcd5e8a755ce92b46b
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:00
create-version=1
source=select `aph`.`no_payment_ap` AS `no_payment_ap`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `supplier_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_supplier` AS `id_supplier`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_purchase` AS `no_purchase`,`apd`.`invoice_date` AS `invoice_date`,`apd`.`ap_amount` AS `ap_amount`,`apd`.`discount` AS `discount`,sum(`apd`.`ap_amount_net`) AS `ap_amount_net`,(`cd`.`paid_amount` - `apd`.`paid_amount`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,`apd`.`ap_return` AS `ap_return`,`ms`.`city` AS `city`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,`apd`.`paid_amount` AS `pembayaran` from ((((`trn_payment_ap_head` `aph` join `trn_payment_ap_det` `apd` on((`aph`.`no_payment_ap` = `apd`.`no_payment_ap`))) join `ap_status` `cd` on((`cd`.`no_purchase` = `apd`.`no_purchase`))) join `mst_supplier` `ms` on((`ms`.`id_supplier` = `aph`.`id_supplier`))) join `mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`))) group by `apd`.`no_purchase`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `aph`.`no_payment_ap` AS `no_payment_ap`,concat((case when isnull(`ms`.`first_name`) then \'\' else `ms`.`first_name` end),(case when isnull(`ms`.`last_name`) then \'\' else `ms`.`last_name` end)) AS `supplier_name`,`aph`.`date_trn` AS `date_trn`,`aph`.`notes` AS `notes`,0 AS `total`,`ma`.`account_name` AS `account_name`,`aph`.`id_supplier` AS `id_supplier`,`aph`.`id_account` AS `id_account`,`apd`.`number_asc` AS `number_asc`,`apd`.`no_purchase` AS `no_purchase`,`apd`.`invoice_date` AS `invoice_date`,`apd`.`ap_amount` AS `ap_amount`,`apd`.`discount` AS `discount`,sum(`apd`.`ap_amount_net`) AS `ap_amount_net`,(`cd`.`paid_amount` - `apd`.`paid_amount`) AS `paid_amount`,concat(`ms`.`address`,\' \',`ms`.`city`) AS `supplier_addr`,`apd`.`ap_return` AS `ap_return`,`ms`.`city` AS `city`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,`apd`.`paid_amount` AS `pembayaran` from ((((`ideaccounting_dev`.`trn_payment_ap_head` `aph` join `ideaccounting_dev`.`trn_payment_ap_det` `apd` on((`aph`.`no_payment_ap` = `apd`.`no_payment_ap`))) join `ideaccounting_dev`.`ap_status` `cd` on((`cd`.`no_purchase` = `apd`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `ms` on((`ms`.`id_supplier` = `aph`.`id_supplier`))) join `ideaccounting_dev`.`mst_account` `ma` on((`ma`.`id_account` = `aph`.`id_account`))) group by `apd`.`no_purchase`
