TYPE=VIEW
query=select `a`.`id_customer` AS `id_customer`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_sales_order` AS `no_sales_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,((case when isnull(`a`.`total`) then 0 else `a`.`total` end) - (case when isnull(`a`.`freight_est`) then 0 else `a`.`freight_est` end)) AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,(case when isnull(`c`.`sent_qty`) then 0 else `c`.`sent_qty` end) AS `sent_qty`,(((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) AS `price`,((((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) * `c`.`qty`) AS `total`,(case when isnull(`a`.`kurs`) then 1 else `a`.`kurs` end) AS `kurs`,`a`.`discount` AS `discount`,`a`.`nett_total` AS `nett_total`,(case when isnull(`a`.`uang_muka`) then 0 else `a`.`uang_muka` end) AS `uang_muka` from ((((((`ideaccounting_dev`.`trn_sales_order_head` `a` join `ideaccounting_dev`.`mst_customer` `b` on((`b`.`id_customer` = `a`.`id_customer`))) join `ideaccounting_dev`.`trn_sales_order_det` `c` on((`c`.`no_sales_order` = `a`.`no_sales_order`))) join `ideaccounting_dev`.`mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) left join `ideaccounting_dev`.`trn_so_discbrand_det` `x` on(((`x`.`no_sales_order` = `c`.`no_sales_order`) and (`x`.`id_item` = `c`.`id_item`)))) left join `ideaccounting_dev`.`trn_so_disccat_det` `y` on(((`y`.`no_sales_order` = `c`.`no_sales_order`) and (`y`.`id_item` = `c`.`id_item`)))) left join `ideaccounting_dev`.`trn_so_disctype_det` `z` on(((`z`.`no_sales_order` = `c`.`no_sales_order`) and (`z`.`id_item` = `c`.`id_item`))))
md5=3149bb446fba15adb3c5e97f8d79b238
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:06
create-version=1
source=select `a`.`id_customer` AS `id_customer`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_sales_order` AS `no_sales_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,((case when isnull(`a`.`total`) then 0 else `a`.`total` end) - (case when isnull(`a`.`freight_est`) then 0 else `a`.`freight_est` end)) AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,(case when isnull(`c`.`sent_qty`) then 0 else `c`.`sent_qty` end) AS `sent_qty`,(((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) AS `price`,((((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) * `c`.`qty`) AS `total`,(case when isnull(`a`.`kurs`) then 1 else `a`.`kurs` end) AS `kurs`,`a`.`discount` AS `discount`,`a`.`nett_total` AS `nett_total`,(case when isnull(`a`.`uang_muka`) then 0 else `a`.`uang_muka` end) AS `uang_muka` from ((((((`trn_sales_order_head` `a` join `mst_customer` `b` on((`b`.`id_customer` = `a`.`id_customer`))) join `trn_sales_order_det` `c` on((`c`.`no_sales_order` = `a`.`no_sales_order`))) join `mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) left join `trn_so_discbrand_det` `x` on(((`x`.`no_sales_order` = `c`.`no_sales_order`) and (`x`.`id_item` = `c`.`id_item`)))) left join `trn_so_disccat_det` `y` on(((`y`.`no_sales_order` = `c`.`no_sales_order`) and (`y`.`id_item` = `c`.`id_item`)))) left join `trn_so_disctype_det` `z` on(((`z`.`no_sales_order` = `c`.`no_sales_order`) and (`z`.`id_item` = `c`.`id_item`))))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`id_customer` AS `id_customer`,concat((case when isnull(`b`.`first_name`) then \'\' else `b`.`first_name` end),\' \',(case when isnull(`b`.`last_name`) then \'\' else `b`.`last_name` end)) AS `nama`,`b`.`address` AS `address`,`a`.`no_sales_order` AS `no_sales_order`,`a`.`date_trn` AS `date_trn`,`c`.`id_curr` AS `id_curr`,`a`.`notes` AS `notes`,`a`.`subtotal` AS `subtotal`,`a`.`tax` AS `tax`,((case when isnull(`a`.`total`) then 0 else `a`.`total` end) - (case when isnull(`a`.`freight_est`) then 0 else `a`.`freight_est` end)) AS `total_head`,`c`.`number_asc` AS `number_asc`,`c`.`id_item` AS `id_item`,`c`.`id_unit` AS `id_unit`,`f`.`item_name` AS `item_name`,`c`.`notes` AS `description`,`c`.`qty` AS `qty`,(case when isnull(`c`.`sent_qty`) then 0 else `c`.`sent_qty` end) AS `sent_qty`,(((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) AS `price`,((((`c`.`price` - ((case when isnull(`x`.`nom_disc`) then 0 else `x`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`y`.`nom_disc`) then 0 else `y`.`nom_disc` end) / `c`.`qty`)) - ((case when isnull(`z`.`nom_disc`) then 0 else `z`.`nom_disc` end) / `c`.`qty`)) * `c`.`qty`) AS `total`,(case when isnull(`a`.`kurs`) then 1 else `a`.`kurs` end) AS `kurs`,`a`.`discount` AS `discount`,`a`.`nett_total` AS `nett_total`,(case when isnull(`a`.`uang_muka`) then 0 else `a`.`uang_muka` end) AS `uang_muka` from ((((((`ideaccounting_dev`.`trn_sales_order_head` `a` join `ideaccounting_dev`.`mst_customer` `b` on((`b`.`id_customer` = `a`.`id_customer`))) join `ideaccounting_dev`.`trn_sales_order_det` `c` on((`c`.`no_sales_order` = `a`.`no_sales_order`))) join `ideaccounting_dev`.`mst_item` `f` on((`f`.`id_item` = `c`.`id_item`))) left join `ideaccounting_dev`.`trn_so_discbrand_det` `x` on(((`x`.`no_sales_order` = `c`.`no_sales_order`) and (`x`.`id_item` = `c`.`id_item`)))) left join `ideaccounting_dev`.`trn_so_disccat_det` `y` on(((`y`.`no_sales_order` = `c`.`no_sales_order`) and (`y`.`id_item` = `c`.`id_item`)))) left join `ideaccounting_dev`.`trn_so_disctype_det` `z` on(((`z`.`no_sales_order` = `c`.`no_sales_order`) and (`z`.`id_item` = `c`.`id_item`))))
