TYPE=VIEW
query=select `a`.`date_trn` AS `date_trn`,`a`.`no_ekspedisi` AS `no_ekspedisi`,`a`.`id_currency` AS `id_currency`,`a`.`notes` AS `notes`,`a`.`total` AS `total`,`a`.`id_account` AS `id_account`,`b`.`no_do` AS `no_do`,`b`.`no_resi` AS `no_resi`,`b`.`freight_address` AS `freight_address`,`b`.`freight_city` AS `freight_city`,`b`.`freight_cost` AS `freight_cost`,`c`.`account_name` AS `account_name`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((`ideaccounting_dev`.`trn_ekspedisi_head` `a` join `ideaccounting_dev`.`trn_ekspedisi_det` `b` on((`b`.`no_ekspedisi` = `a`.`no_ekspedisi`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `a`.`id_account`)))
md5=f1712b10fc93d8be0d7db8ae36dc9859
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:01
create-version=1
source=select `a`.`date_trn` AS `date_trn`,`a`.`no_ekspedisi` AS `no_ekspedisi`,`a`.`id_currency` AS `id_currency`,`a`.`notes` AS `notes`,`a`.`total` AS `total`,`a`.`id_account` AS `id_account`,`b`.`no_do` AS `no_do`,`b`.`no_resi` AS `no_resi`,`b`.`freight_address` AS `freight_address`,`b`.`freight_city` AS `freight_city`,`b`.`freight_cost` AS `freight_cost`,`c`.`account_name` AS `account_name`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from ((`trn_ekspedisi_head` `a` join `trn_ekspedisi_det` `b` on((`b`.`no_ekspedisi` = `a`.`no_ekspedisi`))) join `mst_account` `c` on((`c`.`id_account` = `a`.`id_account`)))
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `a`.`date_trn` AS `date_trn`,`a`.`no_ekspedisi` AS `no_ekspedisi`,`a`.`id_currency` AS `id_currency`,`a`.`notes` AS `notes`,`a`.`total` AS `total`,`a`.`id_account` AS `id_account`,`b`.`no_do` AS `no_do`,`b`.`no_resi` AS `no_resi`,`b`.`freight_address` AS `freight_address`,`b`.`freight_city` AS `freight_city`,`b`.`freight_cost` AS `freight_cost`,`c`.`account_name` AS `account_name`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from ((`ideaccounting_dev`.`trn_ekspedisi_head` `a` join `ideaccounting_dev`.`trn_ekspedisi_det` `b` on((`b`.`no_ekspedisi` = `a`.`no_ekspedisi`))) join `ideaccounting_dev`.`mst_account` `c` on((`c`.`id_account` = `a`.`id_account`)))
