TYPE=VIEW
query=select distinct `a`.`no_sales` AS `no_sales`,cast(`a`.`date_trn` as date) AS `date_trn`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `nama_customer`,`a`.`subtotal` AS `subtotal`,((`a`.`discount` * `a`.`subtotal`) / 100) AS `discount`,(`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100)) AS `subtotal_nett`,((`a`.`tax` / 100) * (`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100))) AS `PPN`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_curr` AS `id_curr` from ((`ideaccounting_dev`.`trn_sales_head` `a` join `ideaccounting_dev`.`trn_sales_det` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`)))
md5=b860b13b2fd26b552a3c2596c05d754d
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:04
create-version=1
source=select distinct `a`.`no_sales` AS `no_sales`,cast(`a`.`date_trn` as date) AS `date_trn`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `nama_customer`,`a`.`subtotal` AS `subtotal`,((`a`.`discount` * `a`.`subtotal`) / 100) AS `discount`,(`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100)) AS `subtotal_nett`,((`a`.`tax` / 100) * (`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100))) AS `PPN`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_curr` AS `id_curr` from ((`trn_sales_head` `a` join `trn_sales_det` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select distinct `a`.`no_sales` AS `no_sales`,cast(`a`.`date_trn` as date) AS `date_trn`,`a`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `nama_customer`,`a`.`subtotal` AS `subtotal`,((`a`.`discount` * `a`.`subtotal`) / 100) AS `discount`,(`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100)) AS `subtotal_nett`,((`a`.`tax` / 100) * (`a`.`subtotal` - ((`a`.`discount` * `a`.`subtotal`) / 100))) AS `PPN`,`a`.`total` AS `total`,`a`.`notes` AS `notes`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_curr` AS `id_curr` from ((`ideaccounting_dev`.`trn_sales_head` `a` join `ideaccounting_dev`.`trn_sales_det` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `a`.`id_customer`)))
