TYPE=VIEW
query=select `ideaccounting_dev`.`mst_item`.`id_item` AS `id_item`,`ideaccounting_dev`.`mst_item`.`item_name` AS `item_name`,`ideaccounting_dev`.`mst_item`.`id_category` AS `id_category`,`ideaccounting_dev`.`mst_item`.`id_jenis` AS `id_jenis`,`ideaccounting_dev`.`mst_item`.`id_account` AS `id_account`,`ideaccounting_dev`.`mst_item`.`main_unit` AS `main_unit`,`ideaccounting_dev`.`mst_item`.`buy_unit` AS `buy_unit`,`ideaccounting_dev`.`mst_item`.`sell_unit` AS `sell_unit`,`ideaccounting_dev`.`mst_item`.`flag_buy` AS `flag_buy`,`ideaccounting_dev`.`mst_item`.`flag_sell` AS `flag_sell`,`ideaccounting_dev`.`mst_item`.`flag_inv` AS `flag_inv`,`ideaccounting_dev`.`mst_item`.`blob_image` AS `blob_image`,`ideaccounting_dev`.`mst_item`.`sell_price` AS `sell_price`,`ideaccounting_dev`.`mst_item`.`modified_user` AS `modified_user`,`ideaccounting_dev`.`mst_item`.`created_date` AS `created_date`,`ideaccounting_dev`.`mst_item`.`modified_date` AS `modified_date`,`ideaccounting_dev`.`mst_item`.`created_user` AS `created_user`,`ideaccounting_dev`.`mst_item`.`id_warehouse` AS `id_warehouse`,`ideaccounting_dev`.`mst_item`.`max_qty` AS `max_qty`,`ideaccounting_dev`.`mst_item`.`min_qty` AS `min_qty`,`ideaccounting_dev`.`mst_item`.`notes` AS `notes`,`ideaccounting_dev`.`mst_item`.`length` AS `length`,`ideaccounting_dev`.`mst_item`.`width` AS `width`,`ideaccounting_dev`.`mst_item`.`height` AS `height`,`ideaccounting_dev`.`mst_item`.`weight` AS `weight`,(case when isnull(`ideaccounting_dev`.`mst_item`.`id_barcode`) then \'\' else `ideaccounting_dev`.`mst_item`.`id_barcode` end) AS `id_barcode`,`ideaccounting_dev`.`mst_itembrand`.`mst_itembrand_nm` AS `brand`,`ideaccounting_dev`.`mst_itemcat`.`mst_itemcat_nm` AS `category`,`ideaccounting_dev`.`mst_itemjenis`.`mst_itemjenis_nm` AS `type`,`ideaccounting_dev`.`mst_item`.`id_brand` AS `id_brand` from (((`ideaccounting_dev`.`mst_item` left join `ideaccounting_dev`.`mst_itembrand` on((`ideaccounting_dev`.`mst_itembrand`.`mst_itembrand_id` = `ideaccounting_dev`.`mst_item`.`id_brand`))) join `ideaccounting_dev`.`mst_itemcat` on((`ideaccounting_dev`.`mst_itemcat`.`mst_itemcat_id` = `ideaccounting_dev`.`mst_item`.`id_category`))) join `ideaccounting_dev`.`mst_itemjenis` on((`ideaccounting_dev`.`mst_itemjenis`.`mst_itemjenis_id` = `ideaccounting_dev`.`mst_item`.`id_jenis`))) where (((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_sell`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_buy` end) = 0) and ((case when isnull(`ideaccounting_dev`.`mst_item`.`active_status`) then 0 else `ideaccounting_dev`.`mst_item`.`active_status` end) <> 0))
md5=49486eae96527f9258e9d7f52396b831
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `mst_item`.`id_item` AS `id_item`,`mst_item`.`item_name` AS `item_name`,`mst_item`.`id_category` AS `id_category`,`mst_item`.`id_jenis` AS `id_jenis`,`mst_item`.`id_account` AS `id_account`,`mst_item`.`main_unit` AS `main_unit`,`mst_item`.`buy_unit` AS `buy_unit`,`mst_item`.`sell_unit` AS `sell_unit`,`mst_item`.`flag_buy` AS `flag_buy`,`mst_item`.`flag_sell` AS `flag_sell`,`mst_item`.`flag_inv` AS `flag_inv`,`mst_item`.`blob_image` AS `blob_image`,`mst_item`.`sell_price` AS `sell_price`,`mst_item`.`modified_user` AS `modified_user`,`mst_item`.`created_date` AS `created_date`,`mst_item`.`modified_date` AS `modified_date`,`mst_item`.`created_user` AS `created_user`,`mst_item`.`id_warehouse` AS `id_warehouse`,`mst_item`.`max_qty` AS `max_qty`,`mst_item`.`min_qty` AS `min_qty`,`mst_item`.`notes` AS `notes`,`mst_item`.`length` AS `length`,`mst_item`.`width` AS `width`,`mst_item`.`height` AS `height`,`mst_item`.`weight` AS `weight`,(case when isnull(`mst_item`.`id_barcode`) then \'\' else `mst_item`.`id_barcode` end) AS `id_barcode`,`mst_itembrand`.`mst_itembrand_nm` AS `brand`,`mst_itemcat`.`mst_itemcat_nm` AS `category`,`mst_itemjenis`.`mst_itemjenis_nm` AS `type`,`mst_item`.`id_brand` AS `id_brand` from (((`mst_item` left join `mst_itembrand` on((`mst_itembrand`.`mst_itembrand_id` = `mst_item`.`id_brand`))) join `mst_itemcat` on((`mst_itemcat`.`mst_itemcat_id` = `mst_item`.`id_category`))) join `mst_itemjenis` on((`mst_itemjenis`.`mst_itemjenis_id` = `mst_item`.`id_jenis`))) where (((case when isnull(`mst_item`.`flag_sell`) then 0 else `mst_item`.`flag_buy` end) = 0) and ((case when isnull(`mst_item`.`active_status`) then 0 else `mst_item`.`active_status` end) <> 0))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `ideaccounting_dev`.`mst_item`.`id_item` AS `id_item`,`ideaccounting_dev`.`mst_item`.`item_name` AS `item_name`,`ideaccounting_dev`.`mst_item`.`id_category` AS `id_category`,`ideaccounting_dev`.`mst_item`.`id_jenis` AS `id_jenis`,`ideaccounting_dev`.`mst_item`.`id_account` AS `id_account`,`ideaccounting_dev`.`mst_item`.`main_unit` AS `main_unit`,`ideaccounting_dev`.`mst_item`.`buy_unit` AS `buy_unit`,`ideaccounting_dev`.`mst_item`.`sell_unit` AS `sell_unit`,`ideaccounting_dev`.`mst_item`.`flag_buy` AS `flag_buy`,`ideaccounting_dev`.`mst_item`.`flag_sell` AS `flag_sell`,`ideaccounting_dev`.`mst_item`.`flag_inv` AS `flag_inv`,`ideaccounting_dev`.`mst_item`.`blob_image` AS `blob_image`,`ideaccounting_dev`.`mst_item`.`sell_price` AS `sell_price`,`ideaccounting_dev`.`mst_item`.`modified_user` AS `modified_user`,`ideaccounting_dev`.`mst_item`.`created_date` AS `created_date`,`ideaccounting_dev`.`mst_item`.`modified_date` AS `modified_date`,`ideaccounting_dev`.`mst_item`.`created_user` AS `created_user`,`ideaccounting_dev`.`mst_item`.`id_warehouse` AS `id_warehouse`,`ideaccounting_dev`.`mst_item`.`max_qty` AS `max_qty`,`ideaccounting_dev`.`mst_item`.`min_qty` AS `min_qty`,`ideaccounting_dev`.`mst_item`.`notes` AS `notes`,`ideaccounting_dev`.`mst_item`.`length` AS `length`,`ideaccounting_dev`.`mst_item`.`width` AS `width`,`ideaccounting_dev`.`mst_item`.`height` AS `height`,`ideaccounting_dev`.`mst_item`.`weight` AS `weight`,(case when isnull(`ideaccounting_dev`.`mst_item`.`id_barcode`) then \'\' else `ideaccounting_dev`.`mst_item`.`id_barcode` end) AS `id_barcode`,`ideaccounting_dev`.`mst_itembrand`.`mst_itembrand_nm` AS `brand`,`ideaccounting_dev`.`mst_itemcat`.`mst_itemcat_nm` AS `category`,`ideaccounting_dev`.`mst_itemjenis`.`mst_itemjenis_nm` AS `type`,`ideaccounting_dev`.`mst_item`.`id_brand` AS `id_brand` from (((`ideaccounting_dev`.`mst_item` left join `ideaccounting_dev`.`mst_itembrand` on((`ideaccounting_dev`.`mst_itembrand`.`mst_itembrand_id` = `ideaccounting_dev`.`mst_item`.`id_brand`))) join `ideaccounting_dev`.`mst_itemcat` on((`ideaccounting_dev`.`mst_itemcat`.`mst_itemcat_id` = `ideaccounting_dev`.`mst_item`.`id_category`))) join `ideaccounting_dev`.`mst_itemjenis` on((`ideaccounting_dev`.`mst_itemjenis`.`mst_itemjenis_id` = `ideaccounting_dev`.`mst_item`.`id_jenis`))) where (((case when isnull(`ideaccounting_dev`.`mst_item`.`flag_sell`) then 0 else `ideaccounting_dev`.`mst_item`.`flag_buy` end) = 0) and ((case when isnull(`ideaccounting_dev`.`mst_item`.`active_status`) then 0 else `ideaccounting_dev`.`mst_item`.`active_status` end) <> 0))
