TYPE=VIEW
query=select `a`.`no_sales` AS `no_sales`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`a`.`price` AS `price`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from (((`ideaccounting_dev`.`trn_sales_det` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item` order by sum(`a`.`qty`) desc
md5=a79c9c81f0f8caba220d796374b38a03
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_sales` AS `no_sales`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`a`.`price` AS `price`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city` from (((`trn_sales_det` `a` join `trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) join `mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item` order by sum(`a`.`qty`) desc
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_sales` AS `no_sales`,`a`.`id_item` AS `id_item`,`d`.`item_name` AS `item_name`,`b`.`date_trn` AS `date_trn`,sum(`a`.`qty`) AS `qty`,`b`.`id_customer` AS `id_customer`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `customer_name`,`a`.`price` AS `price`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city` from (((`ideaccounting_dev`.`trn_sales_det` `a` join `ideaccounting_dev`.`trn_sales_head` `b` on((`b`.`no_sales` = `a`.`no_sales`))) join `ideaccounting_dev`.`mst_customer` `c` on((`c`.`id_customer` = `b`.`id_customer`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `a`.`id_item`))) group by `a`.`id_item` order by sum(`a`.`qty`) desc
