TYPE=VIEW
query=select `a`.`no_purchase` AS `no_purchase`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,`b`.`notes` AS `notes`,`b`.`payment_term_days` AS `payment_term_days`,`a`.`purchase_amount` AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_supplier` AS `id_supplier`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then (((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `ideaccounting_dev`.`mst_currency`.`id_currency` from `ideaccounting_dev`.`mst_currency` where (`ideaccounting_dev`.`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) where (`b`.`payment_method` = 2)
md5=e429e281d2a9cd61536d5091416308f5
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:05
create-version=1
source=select `a`.`no_purchase` AS `no_purchase`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,`b`.`notes` AS `notes`,`b`.`payment_term_days` AS `payment_term_days`,`a`.`purchase_amount` AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `mst_company`.`company_name` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_name`,(select `mst_company`.`address` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_address`,(select `mst_company`.`city` from `mst_company` where (`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_supplier` AS `id_supplier`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then (((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `mst_currency`.`id_currency` from `mst_currency` where (`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ap_status` `a` join `trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) where (`b`.`payment_method` = 2)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`no_purchase` AS `no_purchase`,`a`.`date_trn` AS `date_trn`,concat((case when isnull(`c`.`first_name`) then \'\' else `c`.`first_name` end),\' \',(case when isnull(`c`.`last_name`) then \'\' else `c`.`last_name` end)) AS `supplier_name`,`b`.`notes` AS `notes`,`b`.`payment_term_days` AS `payment_term_days`,`a`.`purchase_amount` AS `purchase_amount`,(case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end) AS `return_amount`,(select `ideaccounting_dev`.`mst_company`.`company_name` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_name`,(select `ideaccounting_dev`.`mst_company`.`address` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_address`,(select `ideaccounting_dev`.`mst_company`.`city` from `ideaccounting_dev`.`mst_company` where (`ideaccounting_dev`.`mst_company`.`flag_active` = 1)) AS `company_city`,`b`.`id_supplier` AS `id_supplier`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0) else 0 end) AS `est_disc`,(case when ((to_days(now()) - to_days(`a`.`date_trn`)) <= `b`.`disc_term_days`) then (((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - round(((`b`.`disc_term_nominal` * `a`.`purchase_amount`) / 100),0)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) else ((`a`.`purchase_amount` - (case when isnull(`a`.`return_amount`) then 0 else `a`.`return_amount` end)) - (case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end)) end) AS `total`,(case when isnull(`a`.`paid_amount`) then 0 else `a`.`paid_amount` end) AS `paid_amount`,(select `ideaccounting_dev`.`mst_currency`.`id_currency` from `ideaccounting_dev`.`mst_currency` where (`ideaccounting_dev`.`mst_currency`.`flag_default` = 1)) AS `curr` from ((`ideaccounting_dev`.`ap_status` `a` join `ideaccounting_dev`.`trn_purchase_head` `b` on((`b`.`no_purchase` = `a`.`no_purchase`))) join `ideaccounting_dev`.`mst_supplier` `c` on((`c`.`id_supplier` = `b`.`id_supplier`))) where (`b`.`payment_method` = 2)
