TYPE=VIEW
query=select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_material_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_wip_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`cost_name` AS `item_detail`,\'conversion\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_conversion_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_standard_cost` `d` on((`d`.`id_cost` = `c`.`id_cost`)))
md5=a9e07eaa0b6e8ddd536a5d5a56be527e
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-02-17 15:32:06
create-version=1
source=select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`trn_wo_realized_head` `a` join `trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `trn_wo_realized_material_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`trn_wo_realized_head` `a` join `trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `trn_wo_realized_wip_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`cost_name` AS `item_detail`,\'conversion\' AS `type` from (((`trn_wo_realized_head` `a` join `trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `trn_wo_realized_conversion_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `mst_standard_cost` `d` on((`d`.`id_cost` = `c`.`id_cost`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_material_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`item_name` AS `item_detail`,\'material\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_wip_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_item` `d` on((`d`.`id_item` = `c`.`id_item`))) union all select `a`.`realized_no` AS `realized_no`,`a`.`pic` AS `pic`,`a`.`cost_total` AS `cost_total`,`a`.`date_trn` AS `date_trn`,`b`.`item_name` AS `item_name`,`d`.`cost_name` AS `item_detail`,\'conversion\' AS `type` from (((`ideaccounting_dev`.`trn_wo_realized_head` `a` join `ideaccounting_dev`.`trn_wo_realized_item_det` `b` on((`b`.`realized_no` = `a`.`realized_no`))) left join `ideaccounting_dev`.`trn_wo_realized_conversion_det` `c` on((`c`.`realized_no` = `a`.`realized_no`))) join `ideaccounting_dev`.`mst_standard_cost` `d` on((`d`.`id_cost` = `c`.`id_cost`)))
